[package]
name = "ignite-rs_derive"
version = "0.1.0"
authors = ["Andrii Pohrebniak <a.pohrebniak@gethatch.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.29"
quote = "1.0.6"
proc-macro2 = "1.0.18"