name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      ignite:
        image: apacheignite/ignite:2.15.0
        ports:
          - 10800:10800
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -qq openjdk-8-jre openjdk-8-jdk wget maven
          wget -q https://repo1.maven.org/maven2/org/apache/ignite/ignite-core/2.15.0/ignite-core-2.15.0.jar
          wget -q https://repo.maven.apache.org/maven2/sqlline/sqlline/1.12.0/sqlline-1.12.0-jar-with-dependencies.jar
          java -cp "./*" sqlline.SqlLine -d org.apache.ignite.IgniteJdbcThinDriver -u jdbc:ignite:thin://127.0.0.1 -n ignite -p ignite -e 'select 1'

      - name: Test
        run: |
          cargo test
